SignalRRestoran/SignalRProject.UI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UdemySignalRProject.UI.Dtos;
using UdemySignalRProject.UI.IApiServices;

namespace UdemySignalRProject.UI.Controllers
{
    [AllowAnonymous]

    public class DefaultController : Controller
    {
        private readonly IMessageApiService _messageApiService;

        public DefaultController(IMessageApiService messageApiService)
        {
            _messageApiService = messageApiService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public PartialViewResult SendMessage()
        {
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> SendMessage(CreateMessageDto createMessageDto)
        {
            var response = await _messageApiService.CrateAsync(createMessageDto, "Messages");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(createMessageDto);
        }
    }
}

SignalRRestoran/SignalRProject.UI/Controllers/MailController.cs
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using UdemySignalRProject.UI.Dtos;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace UdemySignalRProject.UI.Controllers
{
    public class MailController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(CreateMailDto createMailDto)
        {
            MimeMessage mimeMessage = new MimeMessage();
            MailboxAddress mailBoxAdress = new MailboxAddress("SignalR Rezervasyon", "serhatkaratasli790@gmail.com");
            mimeMessage.From.Add(mailBoxAdress);

            MailboxAddress mailboxAddressTo = new MailboxAddress("User", createMailDto.ReceiverMail);
            mimeMessage.To.Add(mailboxAddressTo);

            var bodyBuilder = new BodyBuilder();

            bodyBuilder.TextBody = createMailDto.Body;
            mimeMessage.Body = bodyBuilder.ToMessageBody();

            mimeMessage.Subject = createMailDto.Subject;

            SmtpClient smtpClient = new SmtpClient();
            smtpClient.Connect("smtp.gmail.com", 587, false);
            smtpClient.Authenticate("serhatkaratasli790@gmail.com", "yfzu lynk dxjk nmqa");
            smtpClient.Send(mimeMessage);
            smtpClient.Disconnect(true);
            return RedirectToAction("Index", "Booking");
        }
    }
}

SignalRRestoran/SignalRProject.UI/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;
using UdemySignalRProject.UI.Dtos;
using UdemySignalRProject.UI.IApiServices;

namespace UdemySignalRProject.UI.Controllers
{
    public class MenuController : Controller
    {
        private readonly IProductApiService _productApiService;
        private readonly IBasketApiService _basketApiService;
        public MenuController(IProductApiService productApiService, IBasketApiService basketApiService)
        {
            _productApiService = productApiService;
            _basketApiService = basketApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _productApiService.GetListAsync("Product"));
        }
        [HttpPost]
        public async Task<IActionResult> AddBasket(int id)
        {
            CreateBasketDto createBasketDto = new CreateBasketDto();
            createBasketDto.ProductId = id;
                var response = await _basketApiService.CrateAsync(createBasketDto, "Baskets");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");

            }
            return Json(createBasketDto);
        }
    }
}

SignalRRestoran/SignalRProject.UI/Controllers/QrCodeController.cs
using Microsoft.AspNetCore.Mvc;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace UdemySignalRProject.UI.Controllers
{
    public class QrCodeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string value)
        {
            using (MemoryStream memoryStream = new MemoryStream())
            {
                QRCodeGenerator createQrCode = new QRCodeGenerator();

                QRCodeGenerator.QRCode squareCode = createQrCode.CreateQrCode(value, QRCodeGenerator.ECCLevel.Q);

                using (Bitmap image = squareCode.GetGraphic(10))
                {

                    image.Save(memoryStream, ImageFormat.Png);
                    ViewBag.OrCodeImage = "data:image/png;base64," + Convert.ToBase64String(memoryStream.ToArray());
                }
            }
            return View();
        }
    }
}

SignalRRestoran/SignalRProject.UI/Controllers/SliderController.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using UdemySignalRProject.UI.Dtos;
using UdemySignalRProject.UI.IApiServices;

namespace UdemySignalRProject.UI.Controllers
{
    public class SliderController : Controller
    {

        private readonly ISliderApiService _sliderApiService;
        private readonly IDataProtector _dataProtector;

        public SliderController(ISliderApiService sliderApiService, IDataProtectionProvider dataProtectionProvider)
        {
            _sliderApiService = sliderApiService;
            _dataProtector = dataProtectionProvider.CreateProtector("SliderController");
        }

        public async Task<IActionResult> Index()
        {
            var response = await _sliderApiService.GetListAsync("Sliders");
            response.ForEach(x => { x.DataProtector = _dataProtector.Protect(x.SliderId.ToString()); });

            return View(response);
        }

        [HttpGet]
        public IActionResult CreateSlider()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateSlider(CreateSliderDto createSliderDto)
        {

            var responseMessage = await _sliderApiService.CrateAsync(createSliderDto, "Sliders");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));

            }

            return View();

        }

        public async Task<IActionResult> Delete(string id)
        {
            var dataUnprodected = int.Parse(_dataProtector.Unprotect(id));

            var response = await _sliderApiService.DeleteAsync(dataUnprodected, "Sliders");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var dataUnprodected = int.Parse(_dataProtector.Unprotect(id));
            var responseData = await _sliderApiService.UpdateGetByIdAsync(dataUnprodected, "Sliders");
            return View(responseData);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UpdateSliderDto updateSliderDto)
        {
            var responseMessage = await _sliderApiService.UpdateAsync(updateSliderDto, "Sliders");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));

            }

            return View();

        }
    }
}

SignalRRestoran/SignalRProject.UI/Views/Shared/Components/_LayoutSidebarPartialComponent/Default.cshtml
<div class="sidebar">
    <div class="scrollbar-inner sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <img src="~/Ready-Bootstrap-Dashboard-master/assets/img/profile.jpg">
            </div>
            <div class="info">
                <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                    <span>
                        Yönetim Paneli
                        <span class="user-level">Administrator</span>
                        <span class="caret"></span>
                    </span>
                </a>
                <div class="clearfix"></div>

                <div class="collapse in" id="collapseExample" aria-expanded="true" style="">
                    <ul class="nav">
                        <li>
                            <a asp-controller="Menu" asp-action="Index">
                                <span class="link-collapse">Menüyü Gör</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Register" asp-action="Index">
                                <span class="link-collapse">Yeni Kayıt</span>
                            </a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a asp-controller="Login" asp-action="LogOut">
                                    <span class="link-collapse">Çıkış Yap</span>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a asp-controller="Login" asp-action="Index">
                                    <span class="link-collapse">Giriş Yap</span>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a asp-controller="Default" asp-action="Index" target="_blank">
                    <i class="la la-motorcycle"></i>
                    <p>Siteye Git</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="index.html">
                    <i class="la la-dashboard"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Menu" asp-action="Index">
                    <i class="la la-music"></i>
                    <p>Menüyü Gör</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Category" asp-action="Index">
                    <i class="la la-keyboard-o"></i>
                    <p>Kategoriler</p>
                </a>
            </li>
            <li class="nav-item active">
                <a asp-controller="Product" asp-action="Index">
                    <i class="la la-birthday-cake"></i>
                    <p>Ürünler</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Booking">
                    <i class="la la-bell"></i>
                    <p>Rezervasyonlar</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="About">
                    <i class="la la-font"></i>
                    <p>Hakkımızda</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Contact">
                    <i class="la la-phone-square"></i>
                    <p>İletişim</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Discount" asp-action="Index">
                    <i class="la la-money"></i>
                    <p>İndirimler</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Slider" asp-action="Index">
                    <i class="la la-gamepad"></i>
                    <p>Öne Çıkanlar</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="SocialMedia" asp-action="Index">
                    <i class="la la-map-marker"></i>
                    <p>Sosyal Medya</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Testimonial" asp-action="Index">
                    <i class="la la-group"></i>
                    <p>Referanslar</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Statistic">
                    <i class="la la-pie-chart"></i>
                    <p>İstatistikler</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Notifications">
                    <i class="la la-umbrella"></i>
                    <p>Bildirimler</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="MenuTable">
                    <i class="la la-table"></i>
                    <p>Masalar</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="MenuTableListByStatus" asp-controller="MenuTable">
                    <i class="la la-ship"></i>
                    <p>Masa Durumları</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Messages">
                    <i class="la la-wechat"></i>
                    <p>Mesaj Sayfası</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="ProgressBars" asp-action="Index">
                    <i class="la la-bar-chart"></i>
                    <p>Anlık Durum Çubuğu</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Setting" asp-action="Index">
                    <i class="la la-chain"></i>
                    <p>Ayarlar</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Mail" asp-action="Index">
                    <i class="la la-anchor"></i>
                    <p>Mail İşlemleri</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="QrCode" asp-action="Index">
                    <i class="la la-qrcode"></i>
                    <p>Qr Code İşlemleri</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Login" asp-action="LogOut">
                    <i class="la la-close"></i>
                    <p>Çıkış Yap</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Login" asp-action="LogOut">
                    <i class="la la-close"></i>
                    <p>Çıkış Yap</p>
                </a>
            </li>
        </ul>
    </div>
</div>